In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [ ]:
dataset=load_iris()

In [ ]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [ ]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)

In [ ]:
print(dataset.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
df["target"]=dataset.target

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [ ]:
df_copy=df[df["target"]!=2]

In [ ]:
df_copy["target"].unique()

array([0, 1])

In [ ]:
x=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
classification=LogisticRegression(max_iter=200)

In [ ]:
classification

LogisticRegression(max_iter=200)

In [ ]:
classification.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [ ]:

y_pred=classification.predict(x_test)


In [ ]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [ ]:
#@title calculation of Metrics,Accuracy,Classifiaction Report

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [ ]:
print(confusion_matrix(y_test,y_pred))

[[12  0]
 [ 0  8]]


In [ ]:
print(accuracy_score(y_test,y_pred))

1.0


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [ ]:
#@title Cross validation

In [ ]:
from sklearn.model_selection import KFold

In [ ]:
cv=KFold(n_splits=5,shuffle=True)

In [ ]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
#These are the scores of all cross validation experiments
scores=cross_val_score(classification,x_train,y_train,scoring='accuracy',cv=cv)

In [ ]:
np.mean(scores)

1.0

In [ ]:
#@title Lets see more complex data

#make a prediction with a multinomial Logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
#define dataset
x,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_redundant=5,n_classes=2,random_state=42)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=42)

In [ ]:
complex_loistic_model=LogisticRegression(max_iter=200)

In [ ]:
complex_loistic_model.fit(x_train,y_train)

LogisticRegression(max_iter=200)

In [ ]:
y_pred_complex=complex_loistic_model.predict(x_test)

In [ ]:
print(confusion_matrix(y_test,y_pred_complex))
print(accuracy_score(y_test,y_pred_complex))
print(classification_report(y_test,y_pred_complex))

[[81 19]
 [23 77]]
0.79
              precision    recall  f1-score   support

           0       0.78      0.81      0.79       100
           1       0.80      0.77      0.79       100

    accuracy                           0.79       200
   macro avg       0.79      0.79      0.79       200
weighted avg       0.79      0.79      0.79       200



In [ ]:
cv=KFold(n_splits=5)
cross_val_score(complex_loistic_model,x_train,y_train,cv=cv)

array([0.8375, 0.7875, 0.8375, 0.8625, 0.8   ])

In [ ]:
#@title Hyperparameter Tuning

In [ ]:
#@markdown Grid SearchCV
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [ ]:
parameters={'penalty':('l1','l2','elasticnet'),'C':[1,10,20,30]}


In [ ]:
classifier=LogisticRegression()

In [ ]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [ ]:
#spliting of training data train and validation
clf.fit(x_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20, 30],
                         'penalty': ('l1', 'l2', 'elasticnet')})

In [ ]:
clf.best_params_

{'C': 1, 'penalty': 'l2'}

In [ ]:

clf.best_score_

0.8275

In [ ]:
classifier=LogisticRegression(C=1,penalty='l2')

In [ ]:
classifier.fit(x_train,y_train)

LogisticRegression(C=1)

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
y_pred

array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1])

In [ ]:
classifier.predict_proba(x_test)

array([[8.27439567e-01, 1.72560433e-01],
       [8.53544633e-01, 1.46455367e-01],
       [1.13368459e-01, 8.86631541e-01],
       [2.83765274e-01, 7.16234726e-01],
       [1.42745659e-01, 8.57254341e-01],
       [7.47454472e-01, 2.52545528e-01],
       [9.37948203e-01, 6.20517974e-02],
       [9.62811851e-01, 3.71881494e-02],
       [8.85548407e-01, 1.14451593e-01],
       [9.98686022e-01, 1.31397824e-03],
       [1.43555461e-01, 8.56444539e-01],
       [4.84664599e-01, 5.15335401e-01],
       [3.05707745e-01, 6.94292255e-01],
       [4.40758573e-01, 5.59241427e-01],
       [3.26259494e-01, 6.73740506e-01],
       [8.90954703e-01, 1.09045297e-01],
       [9.25581207e-01, 7.44187933e-02],
       [6.07547733e-01, 3.92452267e-01],
       [9.34638103e-01, 6.53618967e-02],
       [1.75304926e-01, 8.24695074e-01],
       [9.33781798e-01, 6.62182018e-02],
       [1.44598853e-01, 8.55401147e-01],
       [2.24035714e-01, 7.75964286e-01],
       [2.69191345e-01, 7.30808655e-01],
       [3.285424

In [ ]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[81 19]
 [23 77]]
0.79
              precision    recall  f1-score   support

           0       0.78      0.81      0.79       100
           1       0.80      0.77      0.79       100

    accuracy                           0.79       200
   macro avg       0.79      0.79      0.79       200
weighted avg       0.79      0.79      0.79       200



In [ ]:
#@title Randomized Search CV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
random_clf=RandomizedSearchCV(LogisticRegression(),param_distributions=parameters,cv=5,n_iter=20)

In [ ]:
random_clf

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet')})

In [ ]:
random_clf.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=20,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'penalty': ('l1', 'l2', 'elasticnet')})