In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn.decomposition import PCA
from sklearn import datasets

In [3]:
dataset=datasets.load_iris()
X=dataset['data']
y=dataset['target']

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=17)

In [5]:
## PCA- Transformation
pca=PCA(n_components=3)
pca

PCA(n_components=3)

In [8]:
X_train
#here we can observe 4 featres

array([[ 1.93695550e+00,  5.57136244e-02,  7.71835020e-01],
       [ 1.09435957e+00,  1.94053693e-01, -3.75130221e-01],
       [ 1.80645991e-01, -3.47024651e-01, -1.57233030e-01],
       [ 1.60534781e+00,  2.25048193e-01, -1.17124822e-01],
       [ 3.97584910e-01, -5.42537515e-01,  3.45504673e-02],
       [-2.95756948e+00, -3.61571510e-01,  1.74172861e-01],
       [ 1.51530461e+00,  4.65725826e-01, -2.87781679e-01],
       [ 1.45206722e+00, -6.24602594e-01,  3.26008292e-01],
       [ 2.39017811e+00, -9.58224865e-02,  3.36099024e-01],
       [-2.72504764e+00,  2.44057567e-01,  7.42170220e-02],
       [-2.68357079e+00,  3.07130571e-01,  8.74295970e-02],
       [ 2.89364865e+00,  3.31014112e-01, -4.34675406e-01],
       [-2.66837276e+00, -1.91448913e-01, -2.20879593e-01],
       [ 1.34408199e+00, -7.98179128e-01, -3.20179664e-01],
       [ 2.36761175e+00, -2.87307257e-01, -3.02174866e-01],
       [-2.14879114e+00,  8.53424859e-01, -1.05836958e-01],
       [ 1.94712324e+00, -6.71060545e-04

In [9]:
X_train=pca.fit_transform(X_train)
X_train
#now 4 Features got reduced to 3


array([[ 1.93695550e+00,  5.57136244e-02,  7.71835020e-01],
       [ 1.09435957e+00,  1.94053693e-01, -3.75130221e-01],
       [ 1.80645991e-01, -3.47024651e-01, -1.57233030e-01],
       [ 1.60534781e+00,  2.25048193e-01, -1.17124822e-01],
       [ 3.97584910e-01, -5.42537515e-01,  3.45504673e-02],
       [-2.95756948e+00, -3.61571510e-01,  1.74172861e-01],
       [ 1.51530461e+00,  4.65725826e-01, -2.87781679e-01],
       [ 1.45206722e+00, -6.24602594e-01,  3.26008292e-01],
       [ 2.39017811e+00, -9.58224865e-02,  3.36099024e-01],
       [-2.72504764e+00,  2.44057567e-01,  7.42170220e-02],
       [-2.68357079e+00,  3.07130571e-01,  8.74295970e-02],
       [ 2.89364865e+00,  3.31014112e-01, -4.34675406e-01],
       [-2.66837276e+00, -1.91448913e-01, -2.20879593e-01],
       [ 1.34408199e+00, -7.98179128e-01, -3.20179664e-01],
       [ 2.36761175e+00, -2.87307257e-01, -3.02174866e-01],
       [-2.14879114e+00,  8.53424859e-01, -1.05836958e-01],
       [ 1.94712324e+00, -6.71060545e-04

In [11]:
X_test=pca.fit(X_test)

In [12]:
#to know the eigen vector of original features which is used by pca for transformation into 3 featutres
pca.components_


array([[ 0.33183707, -0.07523796,  0.86195918,  0.37583212],
       [ 0.59839181,  0.78647676, -0.15087329, -0.02487564],
       [-0.64095526,  0.51405363,  0.04381921,  0.56833537]])

In [13]:
#percentage spread retained/caugth by 3 new features
pca.explained_variance_ratio_

array([0.92223767, 0.05600767, 0.01510818])